'''
Author: muyi
Date: 2023-07-02 14:57:54
LastEditors: muyi
LastEditTime: 2023-07-02 17:51:56
Description: 
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setimagedirwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setImageDirWidget(QtWidgets.QWidget):
    def setupUi(self, setImageDirWidget):
        setImageDirWidget.setObjectName("setImageDirWidget")
        setImageDirWidget.resize(450, 500)
        setImageDirWidget.setMinimumSize(QtCore.QSize(450, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(setImageDirWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgDirListWidget = QtWidgets.QListWidget(setImageDirWidget)
        self.imgDirListWidget.setStyleSheet("")
        self.imgDirListWidget.setObjectName("imgDirListWidget")
        self.verticalLayout.addWidget(self.imgDirListWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(setImageDirWidget)
        self.add_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.add_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.del_btn = QtWidgets.QPushButton(setImageDirWidget)
        self.del_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.del_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.del_btn.setObjectName("del_btn")
        self.horizontalLayout.addWidget(self.del_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(setImageDirWidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(setImageDirWidget)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(setImageDirWidget)
        QtCore.QMetaObject.connectSlotsByName(setImageDirWidget)

    def retranslateUi(self, setImageDirWidget):
        _translate = QtCore.QCoreApplication.translate
        setImageDirWidget.setWindowTitle(_translate("setImageDirWidget", "搜索目录"))
        self.add_btn.setText(_translate("setImageDirWidget", "+"))
        self.del_btn.setText(_translate("setImageDirWidget", "-"))
        self.cancel_btn.setText(_translate("setImageDirWidget", "取消"))
        self.save_btn.setText(_translate("setImageDirWidget", "确定"))
