'''
Author: muyi
Date: 2023-07-02 14:46:50
LastEditors: muyi
LastEditTime: 2023-07-02 14:55:03
Description: 
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLine = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLine.setObjectName("searchLine")
        self.verticalLayout.addWidget(self.searchLine)
        self.result_listwidget = QtWidgets.QListWidget(self.centralwidget)
        self.result_listwidget.setObjectName("result_listwidget")
        self.verticalLayout.addWidget(self.result_listwidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_addfolder = QtWidgets.QAction(MainWindow)
        self.action_addfolder.setObjectName("action_addfolder")
        self.action_setting = QtWidgets.QAction(MainWindow)
        self.action_setting.setObjectName("action_setting")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_rebuildIndex = QtWidgets.QAction(MainWindow)
        self.action_rebuildIndex.setObjectName("action_rebuildIndex")
        self.menu.addAction(self.action_addfolder)
        self.menu.addAction(self.action_setting)
        self.menu.addAction(self.action_rebuildIndex)
        self.menu_2.addAction(self.action_help)
        self.menu_2.addAction(self.action_about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.action_addfolder.setText(_translate("MainWindow", "添加相册目录"))
        self.action_setting.setText(_translate("MainWindow", "软件设置"))
        self.action_help.setText(_translate("MainWindow", "使用方法"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action_rebuildIndex.setText(_translate("MainWindow", "重新构建索引"))
